export const localImages = [
  require('../assets/images/edit.png'),
  require('../assets/images/email-img.png'),
  require('../assets/images/forgot-password-img.png'),
  require('../assets/images/high-five-pana.png'),
  require('../assets/images/light-bulb.png'),
  require('../assets/images/login-image.png'),
  require('../assets/images/login-image-2.png'),
  require('../assets/images/onboarding-ai.png'),
  require('../assets/images/onboarding-chat.png'),
  require('../assets/images/onboarding-filter.png'),
  require('../assets/images/onboarding-teamup.png'),
  require('../assets/images/orbital-brand.png'),
  require('../assets/images/orbital-logo.png'),
  require('../assets/images/pref-landing-img.png'),
  require('../assets/images/profile-interface.png'),
  require('../assets/images/save-icon.png'),
  require('../assets/images/splash.png')
];
